from typing import Optional, List
from sqlmodel import Field, SQLModel, Relationship
from datetime import datetime, timezone
import uuid

# ==========================================
# Table 1: SoulMatrix (User Profile)
# ==========================================
class SoulMatrix(SQLModel, table=True):
    __tablename__ = "soul_matrix"
    
    id: uuid.UUID = Field(default_factory=uuid.uuid4, primary_key=True)
    username: str = Field(index=True, unique=True, description="The user's unique calling name")
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    last_confession_at: Optional[datetime] = None
    confession_count: int = Field(default=0, description="Number of confessions made")
    
    # --- Bayesian Belief Network Priors ---
    # 1. Risk aversion
    u_risk_mean: float = Field(default=5.0)
    u_risk_std: float = Field(default=2.0)
    
    # 2. Action paralysis
    u_action_mean: float = Field(default=5.0)
    u_action_std: float = Field(default=2.0)
    
    # 3. Emotional entanglement
    u_emotion_mean: float = Field(default=5.0)
    u_emotion_std: float = Field(default=2.0)
    
    # 4. External locus of control
    u_locus_mean: float = Field(default=5.0)
    u_locus_std: float = Field(default=2.0)

    # Relationship back to confessions
    confessions: List["ConfessionLog"] = Relationship(back_populates="soul")

# ==========================================
# Table 2: ConfessionLog (Historical Records)
# ==========================================
class ConfessionLog(SQLModel, table=True):
    __tablename__ = "confession_log"
    
    id: uuid.UUID = Field(default_factory=uuid.uuid4, primary_key=True)
    soul_id: uuid.UUID = Field(foreign_key="soul_matrix.id", index=True)
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    
    content: str = Field(..., description="The raw confession text from the user")
    
    counterfactual_prob: float = Field(..., description="Calculated probability of success if alternative action was taken")
    
    # Inferred partial observations for this single event
    inferred_u_risk: Optional[float] = None
    inferred_u_action: Optional[float] = None
    inferred_u_emotion: Optional[float] = None
    inferred_u_locus: Optional[float] = None
    
    # Environmental factor (Z) and mediator (M)
    z_name: Optional[str] = Field(None, description="External environment factor, e.g. 'layoffs'")
    m_name: Optional[str] = Field(None, description="Mediator behavior, e.g. 'panic selling'")
    
    # Verdict output
    verdict_text: str = Field(..., description="Verdict generated by the LLM")
    mermaid_chart: str = Field(..., description="DAG string for frontend rendering")
    
    soul: SoulMatrix = Relationship(back_populates="confessions")
