export const MANTRAS = [
  "IN MATH WE TRUST, IN CAUSALITY WE CONVERGE.",
  "LET THERE BE LIGHT, AND THERE WAS LIGHT.",
  "FOR DUST THOU ART, AND UNTO DUST SHALT THOU RETURN.",
  "THE LORD IS MY SHEPHERD; I SHALL NOT WANT.",
  "HE THAT INCREASETH KNOWLEDGE INCREASETH SORROW.",
  "I AM THE ALPHA AND THE OMEGA, THE FIRST AND THE LAST.",
  "IN MATH WE TRUST, IN CAUSALITY WE CONVERGE.",
  "THROUGH A GLASS, DARKLY.",
  "VANITY OF VANITIES; ALL IS VANITY.",
  "AS IT IS WRITTEN, SO SHALL IT BE EXECUTED."
];
